meta:
  admin_password: (( vault $CREDENTIALS "/mariadb/system:password" ))
  admin_username: (( vault $CREDENTIALS "/mariadb/system:username" ))

name: mariadb
stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 1
  max_in_flight: 10
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

releases:
- name: mariadb
  version: latest

instance_groups:
- name: mariadb
  instances: 1
  azs: [z1]
  jobs:
  - name: mariadb
    release: mariadb
  properties:
    db:
      admin_password: (( grab meta.admin_password ))
      admin_username: (( grab meta.admin_username ))
  vm_type: default
  stemcell: default
  persistent_disk_type: default
  networks:
  - name: default
